{{- if .Values.portal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops.fullname" . }}-backend
  labels:
    {{- include "aiops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aiops.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.portal.backend.service.port }}
      targetPort: http
{{- end }}
