{{- if eq (include "aiops.managedKeycloakEnabled" .) "true" -}}
{{- $_ := required "authentication.managedKeycloak.database.runtimeExistingSecret is required" .Values.authentication.managedKeycloak.database.runtimeExistingSecret -}}
{{- $_ := required "authentication.managedKeycloak.adminExistingSecret is required" .Values.authentication.managedKeycloak.adminExistingSecret -}}
{{- $_ := required "authentication.managedKeycloak.clientExistingSecret is required" .Values.authentication.managedKeycloak.clientExistingSecret -}}
{{- $_ := required "authentication.managedKeycloak.initialAdminExistingSecret is required" .Values.authentication.managedKeycloak.initialAdminExistingSecret -}}
{{- end -}}
